---
  - name: Installing required Puppet Server packages
    yum: name=puppetserver state=present
    when: masternode|string in ansible_fqdn

  - name: Installing required Puppet Clients  packages
    yum: name=puppet-agent state=present
    when: masternode|string not in ansible_fqdn
